apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.repoName }}
  description: ${{ (values.description or "") | dump }}
  annotations:
    helios.io/port: "${{ values.port }}"
    gitea.org/repo-url: http://localhost:3030/${{ values.owner }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.repoName }}
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=${{ values.repoName }}
    backstage.io/kubernetes-namespace: default
    janus-idp.io/tekton: ${{ values.repoName }}
    tekton.dev/ci-cd: "true"
    argocd/app-name: ${{ values.repoName }}-argocd
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
  {% if values.backendComponent -%}
  dependsOn:
    - component:default/${{ values.backendComponent }}
  {%- endif %}
