apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
type: Opaque
stringData:
  token: ${{ values.token }}
  password: ${{ values.token }}
  username: ${{ values.username }}
  secretToken: ${{ values.webhookSecret }}
