apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
        - image
        - port
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        image:
          title: Image
          type: string
          description: The container image to run (e.g. nginx:latest)
          default: nginx:latest
        port:
          title: Port
          type: number
          description: The port to expose
          default: 80
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # 1. Source Repo
    - id: fetch-source
      name: Fetch Source Code
      action: fetch:template
      input:
        url: ./content/source
        targetPath: ./source
        values:
          name: ${{ parameters.name }}
          image: ${{ parameters.image }}
          port: ${{ parameters.port }}
          description: ${{ parameters.description }}
          owner: ${{ user.entity.metadata.name }}

    - id: publish-source
      name: Publish Source Code
      action: publish:github
      input:
        description: Source Code for ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        sourcePath: ./source
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoVisibility: public

    # 2. GitOps Repo
    - id: fetch-gitops
      name: Fetch GitOps Manifests
      action: fetch:template
      input:
        url: ./content/gitops
        targetPath: ./gitops
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ user.entity.metadata.name }}
          image: ${{ parameters.image }}
          port: ${{ parameters.port }}
          sourceRepo: ${{ steps['publish-source'].output.remoteUrl }}
          gitopsRepo: ${{ steps['publish-source'].output.remoteUrl | replace(".git", "") }}-gitops

    - id: publish-gitops
      name: Publish GitOps Manifests
      action: publish:github
      input:
        description: GitOps Manifests for ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}-gitops
        sourcePath: ./gitops
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoVisibility: public

    # Register Source Component
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-source'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:default/guest
        title: 'Template executed'
        info: 'Your template has been executed'
        severity: 'normal'

  output:
    links:
      - title: Source Repository
        url: ${{ steps['publish-source'].output.remoteUrl }}
      - title: GitOps Repository
        url: ${{ steps['publish-gitops'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
