// database_resources.go handles database credential generation and Secret creation
// for components with database traits.
//
// The CUE engine generates ConfigMaps with database metadata (host, port, name),
// but credentials (username, password) are generated by this Go code for security
// reasons - secrets should never be stored in CUE definitions or GitOps repos.
package controller

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math/big"
	"strings"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/intstr"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"

	appv1alpha1 "github.com/helios-platform-team/helios-platform/apps/operator/api/v1alpha1"
)

const (
	// DefaultPasswordLength is the length of generated passwords
	DefaultPasswordLength = 32

	// DefaultUsernameLength is the length of generated usernames
	DefaultUsernameLength = 16

	// PasswordCharset contains valid characters for password generation
	// Includes uppercase, lowercase, digits, and special characters
	PasswordCharset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+"

	// UsernameCharset contains valid characters for username generation
	// Lowercase letters and digits only for database compatibility
	UsernameCharset = "abcdefghijklmnopqrstuvwxyz0123456789"

	// DatabaseTraitType is the trait type identifier for database traits
	DatabaseTraitType = "database"

	// DefaultPostgresVersion is the default Postgres image tag when not specified.
	DefaultPostgresVersion = "16"

	// DefaultPostgresPort is the default port for Postgres.
	DefaultPostgresPort = 5432

	// DefaultDatabaseStorage is the default PVC size for database volumes.
	DefaultDatabaseStorage = "1Gi"

	// PostgresDataPath is the mount path for Postgres data directory.
	PostgresDataPath = "/var/lib/postgresql/data"

	// PostgresDataSubPath is the subPath within the PVC to avoid lost+found issues.
	PostgresDataSubPath = "pgdata"
)

// DatabaseCredentials holds generated database credentials
type DatabaseCredentials struct {
	Username string
	Password string
}

// DatabaseTraitProperties represents the properties of a database trait
type DatabaseTraitProperties struct {
	DBType  string `json:"dbType"`
	DBName  string `json:"dbName"`
	Port    int    `json:"port"`
	Version string `json:"version"`
	Storage string `json:"storage"`
}

// GenerateSecurePassword generates a cryptographically secure random password
func GenerateSecurePassword(length int) (string, error) {
	if length <= 0 {
		length = DefaultPasswordLength
	}

	password := make([]byte, length)
	charsetLen := big.NewInt(int64(len(PasswordCharset)))

	for i := 0; i < length; i++ {
		idx, err := rand.Int(rand.Reader, charsetLen)
		if err != nil {
			return "", fmt.Errorf("failed to generate random index: %w", err)
		}
		password[i] = PasswordCharset[idx.Int64()]
	}

	return string(password), nil
}

// GenerateSecureUsername generates a cryptographically secure random username
func GenerateSecureUsername(length int) (string, error) {
	if length <= 0 {
		length = DefaultUsernameLength
	}

	// Ensure username starts with a letter (database requirement)
	username := make([]byte, length)
	lettersOnly := "abcdefghijklmnopqrstuvwxyz"
	lettersLen := big.NewInt(int64(len(lettersOnly)))

	// First character must be a letter
	idx, err := rand.Int(rand.Reader, lettersLen)
	if err != nil {
		return "", fmt.Errorf("failed to generate random index: %w", err)
	}
	username[0] = lettersOnly[idx.Int64()]

	// Rest can be letters or digits
	charsetLen := big.NewInt(int64(len(UsernameCharset)))
	for i := 1; i < length; i++ {
		idx, err := rand.Int(rand.Reader, charsetLen)
		if err != nil {
			return "", fmt.Errorf("failed to generate random index: %w", err)
		}
		username[i] = UsernameCharset[idx.Int64()]
	}

	return string(username), nil
}

// GenerateCredentials generates a new set of database credentials
func GenerateCredentials() (*DatabaseCredentials, error) {
	username, err := GenerateSecureUsername(DefaultUsernameLength)
	if err != nil {
		return nil, fmt.Errorf("failed to generate username: %w", err)
	}

	password, err := GenerateSecurePassword(DefaultPasswordLength)
	if err != nil {
		return nil, fmt.Errorf("failed to generate password: %w", err)
	}

	return &DatabaseCredentials{
		Username: username,
		Password: password,
	}, nil
}

// GenerateDatabaseSecret creates a Kubernetes Secret containing database credentials
func GenerateDatabaseSecret(namespace, secretName, componentName string, creds *DatabaseCredentials, dbHost string) *corev1.Secret {
	return &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: namespace,
			Labels: map[string]string{
				"app":                   componentName,
				"helios.io/managed-by":  "operator",
				"helios.io/secret-type": "database-credentials",
			},
		},
		Type: corev1.SecretTypeOpaque,
		Data: map[string][]byte{
			"DB_USER": []byte(creds.Username),
			"DB_PASS": []byte(creds.Password),
			"DB_HOST": []byte(dbHost),
		},
	}
}

// GetDatabaseSecretName returns the conventional secret name for a component
func GetDatabaseSecretName(componentName string) string {
	return fmt.Sprintf("%s-db-secret", componentName)
}

// GetDatabaseHost returns the conventional database host for a component
func GetDatabaseHost(componentName string) string {
	return fmt.Sprintf("%s-db", componentName)
}

// ExtractDatabaseTraits extracts all database traits from HeliosApp components
func ExtractDatabaseTraits(app *appv1alpha1.HeliosApp) []struct {
	ComponentName string
	Properties    DatabaseTraitProperties
} {
	var dbTraits []struct {
		ComponentName string
		Properties    DatabaseTraitProperties
	}

	for _, component := range app.Spec.Components {
		for _, trait := range component.Traits {
			if strings.ToLower(trait.Type) == DatabaseTraitType {
				var props DatabaseTraitProperties
				if trait.Properties != nil && trait.Properties.Raw != nil {
					if err := json.Unmarshal(trait.Properties.Raw, &props); err != nil {
						// Log error but continue - don't fail the entire reconciliation
						continue
					}
				}
				dbTraits = append(dbTraits, struct {
					ComponentName string
					Properties    DatabaseTraitProperties
				}{
					ComponentName: component.Name,
					Properties:    props,
				})
			}
		}
	}

	return dbTraits
}

// reconcileDatabaseSecrets ensures database credential secrets exist for all
// components with database traits. If a secret already exists, it is not modified
// to preserve existing credentials.
func (r *HeliosAppReconciler) reconcileDatabaseSecrets(ctx context.Context, app *appv1alpha1.HeliosApp) error {
	log := logf.FromContext(ctx)

	dbTraits := ExtractDatabaseTraits(app)
	if len(dbTraits) == 0 {
		log.V(1).Info("No database traits found, skipping secret creation")
		return nil
	}

	for _, dbTrait := range dbTraits {
		secretName := GetDatabaseSecretName(dbTrait.ComponentName)
		dbHost := GetDatabaseHost(dbTrait.ComponentName)

		// Check if secret already exists
		existingSecret := &corev1.Secret{}
		err := r.Get(ctx, types.NamespacedName{
			Name:      secretName,
			Namespace: app.Namespace,
		}, existingSecret)

		if err == nil {
			// Secret already exists - do not overwrite to preserve credentials
			log.Info("Database secret already exists, skipping",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			continue
		}

		if !errors.IsNotFound(err) {
			// Unexpected error
			log.Error(err, "Failed to check for existing database secret",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			return fmt.Errorf("failed to check for database secret %s: %w", secretName, err)
		}

		// Secret doesn't exist - generate new credentials
		log.Info("Generating database credentials",
			"component", dbTrait.ComponentName,
			"secret", secretName)

		creds, err := GenerateCredentials()
		if err != nil {
			log.Error(err, "Failed to generate database credentials",
				"component", dbTrait.ComponentName)
			return fmt.Errorf("failed to generate credentials for %s: %w", dbTrait.ComponentName, err)
		}

		// Create the secret
		secret := GenerateDatabaseSecret(app.Namespace, secretName, dbTrait.ComponentName, creds, dbHost)

		// Set owner reference so secret is garbage collected with the HeliosApp
		if err := ctrl.SetControllerReference(app, secret, r.Scheme); err != nil {
			log.Error(err, "Failed to set owner reference for database secret",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			return fmt.Errorf("failed to set owner reference for secret %s: %w", secretName, err)
		}

		if err := r.Create(ctx, secret); err != nil {
			if errors.IsAlreadyExists(err) {
				// Race condition - secret was created between our check and create
				log.Info("Database secret was created concurrently, skipping",
					"component", dbTrait.ComponentName,
					"secret", secretName)
				continue
			}
			log.Error(err, "Failed to create database secret",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			return fmt.Errorf("failed to create database secret %s: %w", secretName, err)
		}

		log.Info("Successfully created database secret",
			"component", dbTrait.ComponentName,
			"secret", secretName,
			"dbHost", dbHost)
	}

	return nil
}

// reconcileDatabaseInstance provisions database StatefulSets and headless
// Services for components with database traits. This runs AFTER
// reconcileDatabaseSecrets so that the credential Secret already exists
// when the StatefulSet is created.
func (r *HeliosAppReconciler) reconcileDatabaseInstance(ctx context.Context, app *appv1alpha1.HeliosApp) error {
	log := logf.FromContext(ctx)

	dbTraits := ExtractDatabaseTraits(app)
	if len(dbTraits) == 0 {
		log.V(1).Info("No database traits found, skipping instance provisioning")
		return nil
	}

	for _, dbTrait := range dbTraits {
		// Only provision postgres instances for now
		if strings.ToLower(dbTrait.Properties.DBType) != "postgres" {
			log.V(1).Info("Skipping non-postgres database type",
				"component", dbTrait.ComponentName,
				"dbType", dbTrait.Properties.DBType)
			continue
		}

		dbHost := GetDatabaseHost(dbTrait.ComponentName)
		secretName := GetDatabaseSecretName(dbTrait.ComponentName)

		// Determine effective database name
		effectiveDBName := dbTrait.Properties.DBName
		if effectiveDBName == "" {
			effectiveDBName = fmt.Sprintf("%s-db", dbTrait.ComponentName)
		}

		// Determine version — CUE schema requires version!, but we
		// guard here defensively in case of direct API usage.
		version := dbTrait.Properties.Version
		if version == "" {
			version = DefaultPostgresVersion
		}

		// Determine port
		port := dbTrait.Properties.Port
		if port <= 0 {
			port = DefaultPostgresPort
		}

		// Determine storage
		storage := dbTrait.Properties.Storage
		if storage == "" {
			storage = DefaultDatabaseStorage
		}

		// --- StatefulSet ---
		sts, err := GenerateDatabaseStatefulSet(
			app.Namespace, dbHost, secretName, effectiveDBName, version, storage, int32(port),
		)
		if err != nil {
			log.Error(err, "Failed to generate database StatefulSet",
				"component", dbTrait.ComponentName, "storage", storage)
			return fmt.Errorf("failed to generate StatefulSet for %s: %w", dbHost, err)
		}

		if err := ctrl.SetControllerReference(app, sts, r.Scheme); err != nil {
			log.Error(err, "Failed to set owner reference for database StatefulSet",
				"component", dbTrait.ComponentName)
			return fmt.Errorf("failed to set owner reference for StatefulSet %s: %w", dbHost, err)
		}

		existingSts := &appsv1.StatefulSet{}
		err = r.Get(ctx, types.NamespacedName{Name: dbHost, Namespace: app.Namespace}, existingSts)
		if err != nil {
			if !errors.IsNotFound(err) {
				return fmt.Errorf("failed to check for StatefulSet %s: %w", dbHost, err)
			}

			log.Info("Creating database StatefulSet",
				"component", dbTrait.ComponentName,
				"statefulset", dbHost,
				"image", fmt.Sprintf("postgres:%s", version))

			if err := r.Create(ctx, sts); err != nil {
				if errors.IsAlreadyExists(err) {
					log.Info("Database StatefulSet was created concurrently, skipping",
						"component", dbTrait.ComponentName)
				} else {
					return fmt.Errorf("failed to create StatefulSet %s: %w", dbHost, err)
				}
			}
		} else {
			// Handle StatefulSet drift: update spec to match the new template
			log.Info("Database StatefulSet already exists, updating if necessary",
				"component", dbTrait.ComponentName,
				"statefulset", dbHost)

			// We only update the mutable fields (Replicas, Template)
			updatedSts := existingSts.DeepCopy()
			updatedSts.Spec.Replicas = sts.Spec.Replicas
			updatedSts.Spec.Template = sts.Spec.Template

			// We need to preserve the existing VolumeClaimTemplates when updating
			updatedSts.Spec.VolumeClaimTemplates = existingSts.Spec.VolumeClaimTemplates

			if err := r.Update(ctx, updatedSts); err != nil {
				return fmt.Errorf("failed to update StatefulSet %s: %w", dbHost, err)
			}
		}

		// --- Headless Service ---
		svc := GenerateDatabaseService(app.Namespace, dbHost, int32(port))

		if err := ctrl.SetControllerReference(app, svc, r.Scheme); err != nil {
			log.Error(err, "Failed to set owner reference for database Service",
				"component", dbTrait.ComponentName)
			return fmt.Errorf("failed to set owner reference for Service %s: %w", dbHost, err)
		}

		existingSvc := &corev1.Service{}
		err = r.Get(ctx, types.NamespacedName{Name: dbHost, Namespace: app.Namespace}, existingSvc)
		if err != nil {
			if !errors.IsNotFound(err) {
				return fmt.Errorf("failed to check for Service %s: %w", dbHost, err)
			}

			log.Info("Creating database headless Service",
				"component", dbTrait.ComponentName,
				"service", dbHost)

			if err := r.Create(ctx, svc); err != nil {
				if errors.IsAlreadyExists(err) {
					log.Info("Database Service was created concurrently, skipping",
						"component", dbTrait.ComponentName)
				} else {
					return fmt.Errorf("failed to create Service %s: %w", dbHost, err)
				}
			}
		} else {
			log.Info("Database Service already exists, updating if necessary",
				"component", dbTrait.ComponentName,
				"service", dbHost)

			updatedSvc := existingSvc.DeepCopy()
			updatedSvc.Spec.Ports = svc.Spec.Ports

			if err := r.Update(ctx, updatedSvc); err != nil {
				return fmt.Errorf("failed to update Service %s: %w", dbHost, err)
			}
		}

		log.Info("Successfully reconciled database instance",
			"component", dbTrait.ComponentName,
			"statefulset", dbHost,
			"dbName", effectiveDBName)
	}

	return nil
}

// GenerateDatabaseStatefulSet creates a StatefulSet for a Postgres database instance.
// The StatefulSet injects POSTGRES_DB from the CRD's database.name value, and
// uses the Secret from Issue #33 for POSTGRES_USER and POSTGRES_PASSWORD.
func GenerateDatabaseStatefulSet(namespace, name, secretName, dbName, version, storage string, port int32) (*appsv1.StatefulSet, error) {
	storageQty, err := resource.ParseQuantity(storage)
	if err != nil {
		return nil, fmt.Errorf("invalid storage size format %q: %w", storage, err)
	}

	replicas := int32(1)
	labels := map[string]string{
		"app":                  name,
		"helios.io/managed-by": "operator",
		"helios.io/trait":      "database",
		"helios.io/db-type":    "postgres",
	}

	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			Labels:    labels,
		},
		Spec: appsv1.StatefulSetSpec{
			ServiceName: name,
			Replicas:    &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{"app": name},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{"app": name},
				},
				Spec: corev1.PodSpec{
					Containers: []corev1.Container{
						{
							Name:  "postgres",
							Image: fmt.Sprintf("postgres:%s", version),
							Ports: []corev1.ContainerPort{
								{
									ContainerPort: port,
									Name:          "postgres",
								},
							},
							Env: []corev1.EnvVar{
								{
									Name:  "POSTGRES_DB",
									Value: dbName,
								},
								{
									Name: "POSTGRES_USER",
									ValueFrom: &corev1.EnvVarSource{
										SecretKeyRef: &corev1.SecretKeySelector{
											LocalObjectReference: corev1.LocalObjectReference{
												Name: secretName,
											},
											Key: "DB_USER",
										},
									},
								},
								{
									Name: "POSTGRES_PASSWORD",
									ValueFrom: &corev1.EnvVarSource{
										SecretKeyRef: &corev1.SecretKeySelector{
											LocalObjectReference: corev1.LocalObjectReference{
												Name: secretName,
											},
											Key: "DB_PASS",
										},
									},
								},
								{
									// PGDATA tells Postgres where to store cluster data.
									// Must match volumeMount + subPath to avoid lost+found conflicts.
									Name:  "PGDATA",
									Value: PostgresDataPath + "/" + PostgresDataSubPath,
								},
								{
									// Ensure consistent UTF-8 encoding for all databases.
									Name:  "POSTGRES_INITDB_ARGS",
									Value: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C",
								},
								{
									// Explicitly set the custom port so that postgres knows to listen on it.
									Name:  "PGPORT",
									Value: fmt.Sprintf("%d", port),
								},
							},
							VolumeMounts: []corev1.VolumeMount{
								{
									Name:      "data",
									MountPath: PostgresDataPath,
									SubPath:   PostgresDataSubPath,
								},
							},
							Resources: corev1.ResourceRequirements{
								Requests: corev1.ResourceList{
									corev1.ResourceCPU:    resourceMustParse("100m"),
									corev1.ResourceMemory: resourceMustParse("256Mi"),
								},
								Limits: corev1.ResourceList{
									corev1.ResourceCPU:    resourceMustParse("500m"),
									corev1.ResourceMemory: resourceMustParse("512Mi"),
								},
							},
							ReadinessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									Exec: &corev1.ExecAction{
										Command: []string{"pg_isready", "-U", "$(POSTGRES_USER)", "-d", dbName, "-p", "$(PGPORT)"},
									},
								},
								InitialDelaySeconds: 5,
								PeriodSeconds:       10,
							},
							LivenessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									Exec: &corev1.ExecAction{
										Command: []string{"pg_isready", "-U", "$(POSTGRES_USER)", "-d", dbName, "-p", "$(PGPORT)"},
									},
								},
								InitialDelaySeconds: 30,
								PeriodSeconds:       10,
							},
						},
					},
				},
			},
			VolumeClaimTemplates: []corev1.PersistentVolumeClaim{
				{
					ObjectMeta: metav1.ObjectMeta{
						Name: "data",
					},
					Spec: corev1.PersistentVolumeClaimSpec{
						AccessModes: []corev1.PersistentVolumeAccessMode{
							corev1.ReadWriteOnce,
						},
						Resources: corev1.VolumeResourceRequirements{
							Requests: corev1.ResourceList{
								corev1.ResourceStorage: storageQty,
							},
						},
					},
				},
			},
		},
	}, nil
}

// GenerateDatabaseService creates a headless Service for a database StatefulSet.
// The headless Service (clusterIP: None) provides stable DNS resolution
// so <name> resolves to the database pod.
func GenerateDatabaseService(namespace, name string, port int32) *corev1.Service {
	labels := map[string]string{
		"app":                  name,
		"helios.io/managed-by": "operator",
		"helios.io/trait":      "database",
	}

	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			Labels:    labels,
		},
		Spec: corev1.ServiceSpec{
			ClusterIP: "None",
			Selector:  map[string]string{"app": name},
			Ports: []corev1.ServicePort{
				{
					Port:       port,
					TargetPort: intstr.FromInt32(port),
					Name:       "db",
				},
			},
		},
	}
}

// resourceMustParse is a helper to parse resource quantities. Panics on invalid input.
func resourceMustParse(s string) resource.Quantity {
	return resource.MustParse(s)
}

// GenerateBase64Token generates a random base64-encoded token
// Useful for generating secure webhook secrets or API tokens
func GenerateBase64Token(byteLength int) (string, error) {
	if byteLength <= 0 {
		byteLength = 32
	}

	bytes := make([]byte, byteLength)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("failed to generate random bytes: %w", err)
	}

	return base64.StdEncoding.EncodeToString(bytes), nil
}
