// database_resources.go handles database credential generation and Secret creation
// for components with database traits.
//
// The CUE engine generates ConfigMaps with database metadata (host, port, name),
// but credentials (username, password) are generated by this Go code for security
// reasons - secrets should never be stored in CUE definitions or GitOps repos.
package controller

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math/big"
	"strings"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"

	appv1alpha1 "github.com/helios-platform-team/helios-platform/apps/operator/api/v1alpha1"
)

const (
	// DefaultPasswordLength is the length of generated passwords
	DefaultPasswordLength = 32

	// DefaultUsernameLength is the length of generated usernames
	DefaultUsernameLength = 16

	// PasswordCharset contains valid characters for password generation
	// Includes uppercase, lowercase, digits, and special characters
	PasswordCharset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+"

	// UsernameCharset contains valid characters for username generation
	// Lowercase letters and digits only for database compatibility
	UsernameCharset = "abcdefghijklmnopqrstuvwxyz0123456789"

	// DatabaseTraitType is the trait type identifier for database traits
	DatabaseTraitType = "database"
)

// DatabaseCredentials holds generated database credentials
type DatabaseCredentials struct {
	Username string
	Password string
}

// DatabaseTraitProperties represents the properties of a database trait
type DatabaseTraitProperties struct {
	DBType  string `json:"dbType"`
	DBName  string `json:"dbName"`
	Port    int    `json:"port"`
	Version string `json:"version"`
	Storage string `json:"storage"`
}

// GenerateSecurePassword generates a cryptographically secure random password
func GenerateSecurePassword(length int) (string, error) {
	if length <= 0 {
		length = DefaultPasswordLength
	}

	password := make([]byte, length)
	charsetLen := big.NewInt(int64(len(PasswordCharset)))

	for i := 0; i < length; i++ {
		idx, err := rand.Int(rand.Reader, charsetLen)
		if err != nil {
			return "", fmt.Errorf("failed to generate random index: %w", err)
		}
		password[i] = PasswordCharset[idx.Int64()]
	}

	return string(password), nil
}

// GenerateSecureUsername generates a cryptographically secure random username
func GenerateSecureUsername(length int) (string, error) {
	if length <= 0 {
		length = DefaultUsernameLength
	}

	// Ensure username starts with a letter (database requirement)
	username := make([]byte, length)
	lettersOnly := "abcdefghijklmnopqrstuvwxyz"
	lettersLen := big.NewInt(int64(len(lettersOnly)))

	// First character must be a letter
	idx, err := rand.Int(rand.Reader, lettersLen)
	if err != nil {
		return "", fmt.Errorf("failed to generate random index: %w", err)
	}
	username[0] = lettersOnly[idx.Int64()]

	// Rest can be letters or digits
	charsetLen := big.NewInt(int64(len(UsernameCharset)))
	for i := 1; i < length; i++ {
		idx, err := rand.Int(rand.Reader, charsetLen)
		if err != nil {
			return "", fmt.Errorf("failed to generate random index: %w", err)
		}
		username[i] = UsernameCharset[idx.Int64()]
	}

	return string(username), nil
}

// GenerateCredentials generates a new set of database credentials
func GenerateCredentials() (*DatabaseCredentials, error) {
	username, err := GenerateSecureUsername(DefaultUsernameLength)
	if err != nil {
		return nil, fmt.Errorf("failed to generate username: %w", err)
	}

	password, err := GenerateSecurePassword(DefaultPasswordLength)
	if err != nil {
		return nil, fmt.Errorf("failed to generate password: %w", err)
	}

	return &DatabaseCredentials{
		Username: username,
		Password: password,
	}, nil
}

// GenerateDatabaseSecret creates a Kubernetes Secret containing database credentials
func GenerateDatabaseSecret(namespace, secretName, componentName string, creds *DatabaseCredentials, dbHost string) *corev1.Secret {
	return &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: namespace,
			Labels: map[string]string{
				"app":                   componentName,
				"helios.io/managed-by":  "operator",
				"helios.io/secret-type": "database-credentials",
			},
		},
		Type: corev1.SecretTypeOpaque,
		Data: map[string][]byte{
			"DB_USER": []byte(creds.Username),
			"DB_PASS": []byte(creds.Password),
			"DB_HOST": []byte(dbHost),
		},
	}
}

// GetDatabaseSecretName returns the conventional secret name for a component
func GetDatabaseSecretName(componentName string) string {
	return fmt.Sprintf("%s-db-secret", componentName)
}

// GetDatabaseHost returns the conventional database host for a component
func GetDatabaseHost(componentName string) string {
	return fmt.Sprintf("%s-db", componentName)
}

// ExtractDatabaseTraits extracts all database traits from HeliosApp components
func ExtractDatabaseTraits(app *appv1alpha1.HeliosApp) []struct {
	ComponentName string
	Properties    DatabaseTraitProperties
} {
	var dbTraits []struct {
		ComponentName string
		Properties    DatabaseTraitProperties
	}

	for _, component := range app.Spec.Components {
		for _, trait := range component.Traits {
			if strings.ToLower(trait.Type) == DatabaseTraitType {
				var props DatabaseTraitProperties
				if trait.Properties != nil && trait.Properties.Raw != nil {
					if err := json.Unmarshal(trait.Properties.Raw, &props); err != nil {
						// Log error but continue - don't fail the entire reconciliation
						continue
					}
				}
				dbTraits = append(dbTraits, struct {
					ComponentName string
					Properties    DatabaseTraitProperties
				}{
					ComponentName: component.Name,
					Properties:    props,
				})
			}
		}
	}

	return dbTraits
}

// reconcileDatabaseSecrets ensures database credential secrets exist for all
// components with database traits. If a secret already exists, it is not modified
// to preserve existing credentials.
func (r *HeliosAppReconciler) reconcileDatabaseSecrets(ctx context.Context, app *appv1alpha1.HeliosApp) error {
	log := logf.FromContext(ctx)

	dbTraits := ExtractDatabaseTraits(app)
	if len(dbTraits) == 0 {
		log.V(1).Info("No database traits found, skipping secret creation")
		return nil
	}

	for _, dbTrait := range dbTraits {
		secretName := GetDatabaseSecretName(dbTrait.ComponentName)
		dbHost := GetDatabaseHost(dbTrait.ComponentName)

		// Check if secret already exists
		existingSecret := &corev1.Secret{}
		err := r.Get(ctx, types.NamespacedName{
			Name:      secretName,
			Namespace: app.Namespace,
		}, existingSecret)

		if err == nil {
			// Secret already exists - do not overwrite to preserve credentials
			log.Info("Database secret already exists, skipping",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			continue
		}

		if !errors.IsNotFound(err) {
			// Unexpected error
			log.Error(err, "Failed to check for existing database secret",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			return fmt.Errorf("failed to check for database secret %s: %w", secretName, err)
		}

		// Secret doesn't exist - generate new credentials
		log.Info("Generating database credentials",
			"component", dbTrait.ComponentName,
			"secret", secretName)

		creds, err := GenerateCredentials()
		if err != nil {
			log.Error(err, "Failed to generate database credentials",
				"component", dbTrait.ComponentName)
			return fmt.Errorf("failed to generate credentials for %s: %w", dbTrait.ComponentName, err)
		}

		// Create the secret
		secret := GenerateDatabaseSecret(app.Namespace, secretName, dbTrait.ComponentName, creds, dbHost)

		// Set owner reference so secret is garbage collected with the HeliosApp
		if err := ctrl.SetControllerReference(app, secret, r.Scheme); err != nil {
			log.Error(err, "Failed to set owner reference for database secret",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			return fmt.Errorf("failed to set owner reference for secret %s: %w", secretName, err)
		}

		if err := r.Create(ctx, secret); err != nil {
			if errors.IsAlreadyExists(err) {
				// Race condition - secret was created between our check and create
				log.Info("Database secret was created concurrently, skipping",
					"component", dbTrait.ComponentName,
					"secret", secretName)
				continue
			}
			log.Error(err, "Failed to create database secret",
				"component", dbTrait.ComponentName,
				"secret", secretName)
			return fmt.Errorf("failed to create database secret %s: %w", secretName, err)
		}

		log.Info("Successfully created database secret",
			"component", dbTrait.ComponentName,
			"secret", secretName,
			"dbHost", dbHost)
	}

	return nil
}

// GenerateBase64Token generates a random base64-encoded token
// Useful for generating secure webhook secrets or API tokens
func GenerateBase64Token(byteLength int) (string, error) {
	if byteLength <= 0 {
		byteLength = 32
	}

	bytes := make([]byte, byteLength)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("failed to generate random bytes: %w", err)
	}

	return base64.StdEncoding.EncodeToString(bytes), nil
}
