name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/operator
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: apps/operator/go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
