/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package gitopssync

import (
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	appv1alpha1 "github.com/helios-platform-team/helios-platform/apps/operator/api/v1alpha1"
)

// SerializeHeliosApp takes a HeliosApp CR, deep-copies it, strips volatile and runtime fields,
// and returns clean YAML suitable for storing in a GitOps repository.
//
// This function performs the following cleanup:
// 1. Deep-copies the input CR to prevent mutations to the original object
// 2. Explicitly sets TypeMeta (apiVersion, kind) to ensure valid YAML output
// 3. Strips volatile metadata fields: resourceVersion, uid, creationTimestamp, managedFields
// 4. Strips cluster-generated fields: ownerReferences, finalizers
// 5. Removes kubectl-injected annotations (last-applied-configuration) to reduce noise
// 6. Strips the entire Status subresource (runtime state, not declarative)
//
// The resulting YAML represents only the declarative, user-intent portion of the CR,
// making it ideal for GitOps repository storage and drift detection.
//
// Returns ([]byte, error):
// - On success: YAML bytes representing the clean CR
// - On error: nil bytes and a descriptive error (includes Namespace/Name for debugging)
func SerializeHeliosApp(app *appv1alpha1.HeliosApp) ([]byte, error) {
	// Input validation: fail fast on nil input
	if app == nil {
		return nil, fmt.Errorf("serialize failed: HeliosApp instance is nil")
	}

	// Deep-copy to prevent mutations to the original object
	cleanApp := app.DeepCopy()

	// GOTCHA FIX: Ensure TypeMeta is set (Gotcha A)
	// The Kubernetes API server may not return TypeMeta when fetching objects.
	// We must explicitly set it for the serialized YAML to be valid.
	cleanApp.TypeMeta = metav1.TypeMeta{
		APIVersion: appv1alpha1.GroupVersion.String(),
		Kind:       "HeliosApp",
	}

	// Strip volatile metadata fields that are cluster-managed
	cleanApp.ResourceVersion = ""
	cleanApp.UID = ""
	cleanApp.CreationTimestamp = metav1.Time{}
	cleanApp.ManagedFields = nil

	// Strip cluster-generated fields (not part of declarative intent)
	cleanApp.OwnerReferences = nil // Generated by cluster, not declarative
	cleanApp.Finalizers = nil      // Operator-injected, safer to strip in Phase 0.1

	// GOTCHA FIX: Remove bloated kubectl annotation (Gotcha B)
	// kubectl.kubernetes.io/last-applied-configuration can inflate YAML by 10-50%
	// and causes false drift detection in GitOps systems.
	if cleanApp.Annotations != nil {
		delete(cleanApp.Annotations, "kubectl.kubernetes.io/last-applied-configuration")
		// Clean up empty annotations map to avoid clutter in output
		if len(cleanApp.Annotations) == 0 {
			cleanApp.Annotations = nil
		}
	}

	// Strip the entire Status subresource (runtime state)
	// Status is managed by the controller and should not be in the GitOps source-of-truth.
	// The Status field has omitempty tag, so this will not appear as "status: {}" in YAML.
	cleanApp.Status = appv1alpha1.HeliosAppStatus{}

	// Marshal the cleaned object to YAML format
	output, err := yaml.Marshal(cleanApp)
	if err != nil {
		// Rich error context including Namespace/Name for debugging
		return nil, fmt.Errorf("failed to marshal clean HeliosApp %s/%s to YAML: %w",
			app.Namespace, app.Name, err)
	}

	return output, nil
}
