apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ${{ values.name }}-build-run
  namespace: default
spec:
  pipelineRef:
    name: kaniko-build-push-pipeline

  params:
    - name: image-name
      value: ${{ values.image }}
    - name: image-tag
      value: latest
    - name: dockerfile
      value: ./Dockerfile
    - name: build-context
      value: './'

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  taskRunTemplate:
    serviceAccountName: tekton-builder
