apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=${{ values.name }}
    backstage.io/kubernetes-namespace: default
    janus-idp.io/tekton: ${{ values.name }}
    tekton.dev/ci-cd: "true"
    argocd/app-name: ${{ values.name }}-argocd
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
  providesApis:
    - ${{ values.name }}-api
