apiVersion: app.helios.io/v1alpha1
kind: HeliosApp
metadata:
  name: ${{ values.name }}
  namespace: default
spec:
  owner: ${{ values.owner }}
  description: "React application: ${{ values.name }}"
  gitRepo: ${{ values.sourceRepo }}
  gitBranch: main
  imageRepo: ${{ values.image }}
  gitopsRepo: ${{ values.gitopsRepo }}
  gitopsPath: ${{ values.name }}
  pipelineName: from-code-to-cluster
  webhookSecret: git-credentials-${{ values.name }}
  port: ${{ values.port }}
  testCommand: ${{ values.testCommand }}
  components:
    - name: ${{ values.name }}
      type: web-service
      properties:
        image: ${{ values.image }}:latest
        port: ${{ values.port }}
        replicas: 1
      traits:
        - type: service
          properties:
            port: ${{ values.port }}
